### ISSUE TITLE
HOMEPAGE HTML

### ISSUE THREAD

**Issue by jen2ags** [jen2ags/Karaoke-Kings#3]
-Links to bulma, stylsesheet, JQuery, JavaScript inside HTML
-Title (header)
-Navigation links inside the header to the search form and music library HTML
-Title with description/user instructions
-Ready to begin button and get started will scroll down the page to the user input search form
-Form with artist and song search side by side
-Search button after user input form to pull music video and lyrics
-Section for the music player and lyrics to populate

**Comment by cheryljcruz** [comment]
### What has been added:
- links to style sheets and scripts
- nav bar and logo
- header title
- title with filler description
- ready to begin button  href get started section
- input fields for artist name and song name
- search button next to the search field
### What is still needed:
- Section for music player and lyrics to populate

**Comment by cheryljcruz** [comment]
## added

* section, container, and columns for sound player and lyrics
* reformatted html doc for clear indentations
* edit href your library in nav bar to link to library html
