### ISSUE TITLE
LIBRARY HTML

### ISSUE THREAD

**Issue by jen2ags** [jen2ags/Karaoke-Kings#4]
-Page Title- Your Library
-Section for local storage to populate recent searches
-Populate 5-10 recent searches
-Clear library button under the title
-Each search will list the artist and song name that will link back to the homepage with video and lyrics when clicked
-add footer to match the homepage HTML

**Comment by jen2ags** [comment]
Completed:
-page title
-clear library button
-section for recent searches
-each recent search is provided a button (so it can be clicked to link to homepage in future)
-containers for 5 recent searches

**Comment by jen2ags** [comment]
Next Steps: Start bulma styling on the library html

**Comment by cheryljcruz** [comment]
to do: pagetitle change to " Your Library - Karaoke Kings "
